"""master quiz table

Revision ID: 15b60c634b96
Revises: e89847137fd3
Create Date: 2021-05-14 18:08:49.196818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15b60c634b96'
down_revision = 'e89847137fd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('q1_text', sa.String(length=20), nullable=True),
    sa.Column('q1_type', sa.String(length=10), nullable=True),
    sa.Column('q1_choices', sa.String(length=40), nullable=True),
    sa.Column('q2_text', sa.String(length=20), nullable=True),
    sa.Column('q2_type', sa.String(length=10), nullable=True),
    sa.Column('q2_choices', sa.String(length=40), nullable=True),
    sa.Column('q3_text', sa.String(length=20), nullable=True),
    sa.Column('q3_type', sa.String(length=10), nullable=True),
    sa.Column('q3_choices', sa.String(length=40), nullable=True),
    sa.Column('q4_text', sa.String(length=20), nullable=True),
    sa.Column('q4_type', sa.String(length=10), nullable=True),
    sa.Column('q4_choices', sa.String(length=40), nullable=True),
    sa.Column('q5_text', sa.String(length=20), nullable=True),
    sa.Column('q5_type', sa.String(length=10), nullable=True),
    sa.Column('q5_choices', sa.String(length=40), nullable=True),
    sa.Column('q6_text', sa.String(length=20), nullable=True),
    sa.Column('q6_type', sa.String(length=10), nullable=True),
    sa.Column('q6_choices', sa.String(length=40), nullable=True),
    sa.Column('q7_text', sa.String(length=20), nullable=True),
    sa.Column('q7_type', sa.String(length=10), nullable=True),
    sa.Column('q7_choices', sa.String(length=40), nullable=True),
    sa.Column('q8_text', sa.String(length=20), nullable=True),
    sa.Column('q8_type', sa.String(length=10), nullable=True),
    sa.Column('q8_choices', sa.String(length=40), nullable=True),
    sa.Column('sol1', sa.String(length=20), nullable=True),
    sa.Column('sol2', sa.String(length=20), nullable=True),
    sa.Column('sol3', sa.String(length=20), nullable=True),
    sa.Column('sol4', sa.String(length=20), nullable=True),
    sa.Column('sol5', sa.String(length=20), nullable=True),
    sa.Column('sol6', sa.String(length=20), nullable=True),
    sa.Column('sol7', sa.String(length=20), nullable=True),
    sa.Column('sol8', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz')
    # ### end Alembic commands ###
