"""remove unique user name constraint

Revision ID: 98458577e481
Revises: b54580a8fc88
Create Date: 2021-05-16 23:38:47.109309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98458577e481'
down_revision = 'b54580a8fc88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_name', table_name='user')
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.create_index('ix_user_name', 'user', ['name'], unique=1)
    # ### end Alembic commands ###
