"""alphabet_quiz table

Revision ID: cada240ad7ac
Revises: baba8f3f0ef9
Create Date: 2021-05-08 11:46:26.987092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cada240ad7ac'
down_revision = 'baba8f3f0ef9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alphabet_quiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('testee_id', sa.Integer(), nullable=True),
    sa.Column('q1', sa.Integer(), nullable=True),
    sa.Column('q2', sa.Integer(), nullable=True),
    sa.Column('q3', sa.String(length=4), nullable=True),
    sa.Column('q4', sa.String(length=4), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['testee_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alphabet_quiz')
    # ### end Alembic commands ###
