"""numbers_quiz table

Revision ID: e89847137fd3
Revises: cada240ad7ac
Create Date: 2021-05-08 11:48:02.067794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e89847137fd3'
down_revision = 'cada240ad7ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('numbers_quiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('testee_id', sa.Integer(), nullable=True),
    sa.Column('q1', sa.Integer(), nullable=True),
    sa.Column('q2', sa.String(length=10), nullable=True),
    sa.Column('q3', sa.Integer(), nullable=True),
    sa.Column('q4', sa.String(length=10), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['testee_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('numbers_quiz')
    # ### end Alembic commands ###
